---
baseURL: "https://blog.bossylobster.com/"
languageCode: "en-us"
title: "Bossy Lobster"
metadataformat: "yaml"
paginate: 5
pygmentsUseClasses: true
params:
  author: "Danny Hermes (dhermes@bossylobster.com)"
  subtitle: "A blog by Danny Hermes; musing on tech, mathematics, etc."
  disableReadingTime: true
  customCSS:
  - "css/syntax.css"
  # googleAnalytics: "UA-56716324-1"  # TODO, enable this conditionally
  searchEngineURL: "https://www.google.com/search"
  rss: true
  sidebarRecentLimit: 5
  sidebarText: |
    ![bossylobster](/images/bossy_lobster_350_alpha.png)

    ![dhermes](/images/dhermes_headshot.jpg)
  twitter: "https://twitter.com/bossylobster"
  github: "https://github.com/dhermes"
  truncate: true
  mainSections:
  - post
theme: "hugo-octopress"
publishDir: "public"
staticDir:
- "static"
menus:
 main:
 - name: "All Posts"
   url: "/all-posts"
   weight: -700
 - name: "GitHub"
   url: "https://github.com/dhermes/"
   weight: -600
 - name: "Mathematics"
   url: "/mathematics"
   weight: -500
 - name: "Testimonials"
   url: "/testimonials"
   weight: -400
 - name: "About Me"
   url: "/about-me"
   weight: -300

permalinks:
  pages: "/:title"
  posts: "/:year/:month/:title"

disqusShortname: "bossylobster"
